<?php

/**
 * @file
 * Contains \Drupal\opcions_subscription\SubscriptionAccessControlHandler.
 */

namespace Drupal\opcions_subscription;

use Drupal\Core\Entity\EntityAccessControlHandler;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;

/**
 * Access controller for the Subscription entity.
 *
 * @see \Drupal\opcions_subscription\Entity\Subscription.
 */
class SubscriptionAccessControlHandler extends EntityAccessControlHandler {
  /**
   * {@inheritdoc}
   */
  protected function checkAccess(EntityInterface $entity, $operation, AccountInterface $account) {
    /** @var \Drupal\opcions_subscription\SubscriptionInterface $entity */
    switch ($operation) {
      case 'view':
        return AccessResult::allowedIfHasPermission($account, 'view subscription entities');

      case 'update':
        return AccessResult::allowedIfHasPermission($account, 'edit subscription entities');

      case 'edit':
        return AccessResult::allowedIfHasPermission($account, 'edit subscription entities');

      case 'delete':
        return AccessResult::allowedIfHasPermission($account, 'delete subscription entities');

      case 'administer':
        return AccessResult::allowedIfHasPermission($account, 'administer subscription entities');

    }

    // Unknown operation, no opinion.
    return AccessResult::neutral();
  }

  /**
   * {@inheritdoc}
   */
  protected function checkCreateAccess(AccountInterface $account, array $context, $entity_bundle = NULL) {
    return AccessResult::allowedIfHasPermission($account, 'add subscription entities');
  }

  /**
  * {@inheritdoc}
  */
  protected function checkFieldAccess($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL)
  {
    switch ($field = $field_definition->getName()) {
      case in_array($field, ['status', 'expires_on', 'user_id']):
        return AccessResult::allowedIfHasPermission($account, 'administer subscription entities');
    }

    return parent::checkFieldAccess($operation, $field_definition, $account, $items); // TODO: Change the autogenerated stub
  }

}
