<?php

/**
 * @file
 * Contains opcions_collections.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function opcions_collections_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the opcions_collections module.
    case 'help.page.opcions_collections':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Opcions collection tweaks for guides, series and revistas') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function opcions_collections_theme($existing, $type, $theme, $path)
{
  return [
    'paragraph__article_reference_paragraph' => [
      'render element' => 'elements',
      'preprocess functions' => [
        'template_preprocess_paragraph',
        'template_preprocess_collection_item'
      ]
    ]
  ];
}

/**
 * Implements hook_entity_view().
 */
function opcions_collections_paragraph_view_alter(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode)
{
  \Drupal::service('opcions_collections.paragraph_view_alter')->alter($build, $entity);
}

/**
 * Overrides the reference title if necessary
 */
function template_preprocess_collection_item(&$variables) {
  //kint($variables['content']['field_content_reference'][0]['#node']);
  //$variables['content']['field_content_reference'][0]['#node']->setTitle('Alo');
}
