display:
  default:
    display_title: Maestro
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Desplazamiento
      fields:
        redirect_source__path:
          separator: ', '
        created:
          label: Creado
      filters:
        redirect_redirect__uri:
          expose:
            label: Para
        language:
          expose:
            label: 'Lenguaje original'
  page_1:
    display_title: Página
