label: 'Librería de bloques personalizados'
description: 'Encuentra y administra bloques personalizados.'
display:
  default:
    display_title: Maestro
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Anterior'
            next: 'Siguiente >'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Desplazamiento
      fields:
        info:
          label: 'Descripción del bloque'
          separator: ', '
        type:
          label: 'Tipo de bloque'
          separator: ', '
        changed:
          label: Actualizado
        operations:
          label: Operaciones
      filters:
        info:
          expose:
            label: 'Descripción del bloque'
        type:
          expose:
            label: 'Tipo de bloque'
      title: 'Librería de bloques personalizados'
      empty:
        area_text_custom:
          content: 'No hay bloques personalizados disponibles. '
  page_1:
    display_title: Página
    display_options:
      menu:
        title: 'Librería de bloques personalizados'
