label: Usuarios
description: 'Encontrar y gestionar qué personas interactúan con su sitio.'
display:
  default:
    display_title: Maestro
    display_options:
      exposed_form:
        options:
          submit_button: Filtro
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Anterior'
            next: 'Siguiente >'
            first: '« Primero'
            last: 'Último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Desplazamiento
      fields:
        user_bulk_form:
          label: 'Actualización masiva'
        name:
          label: 'Nombre de usuario'
        status:
          label: Estado
        roles_target_id:
          label: Roles
        created:
          label: 'Miembro durante'
        access:
          label: 'Último acceso'
        operations:
          label: Operaciones
        mail:
          separator: ', '
      filters:
        combine:
          expose:
            label: 'Nombre o correo contienen'
        roles_target_id:
          expose:
            label: Rol
        permission:
          expose:
            label: Permiso
        status:
          group_info:
            label: Estado
            group_items:
              1:
                title: Activo
                value: '1'
              2:
                title: Bloqueado
      title: Usuarios
      empty:
        area_text_custom:
          content: 'No hay personas disponibles.'
      use_more_text: más
  page_1:
    display_title: Página
    display_options:
      menu:
        title: Lista
        description: 'Encontrar y gestionar qué personas interactúan con su sitio.'
      tab_options:
        title: Usuarios
        description: 'Gestionar las cuentas, roles y permisos de usuarios.'
